### ISSUE TITLE
How to display preview in Dropzone element itself, when maxFiles>1?

### ISSUE THREAD

**Issue by ft115637850** [zefoy/ngx-dropzone-wrapper#104]
I'm using dropzone component. I found that only when maxFiles=1,  preview can be displayed in Dropzone element itself. How to display preview in Dropzone element itself,  when maxFiles>1?

**Comment by sconix** [comment]
Its just css styling, so you can just override the styles. The default styles is like thats since with multiple files they are often uploaded paraller so showing only one preview wont make sense.
