### ISSUE TITLE
How to listen remove file event?

### ISSUE THREAD

**Issue by huuquyasb** [zefoy/ngx-dropzone-wrapper#105]
My code upload.component.html `  <dropzone [config]="config" (canceled)="cancelUpload($event)" (removedfile)="onFileRemoved($event)"     [message]="'Click or drag images here to upload'" (error)="onUploadError($event)" (success)="onUploadSuccess($event)"></dropzone>`

upload.component.ts  `  onFileRemoved(event: any) {
    console.log('Removed.');
    console.log(event);
}`
[Remove button](http://prntscr.com/jvjovr)
version 6.1.0

**Comment by huuquyasb** [comment]
I found it. `   init: function() {
      const dz = this;
      dz.on('removedfile', function (file) {
         console.log('file remove', file);
      });
    }`  Thanks dropzone 👍 🥇

**Comment by sconix** [comment]
The output name is removedFile not removedfile if you want to use the Angular events.

**Comment by MooNLightSur** [comment]
In my case, the (removedfile) is called after form submit also
