### ISSUE TITLE
Show thumbnail for manually added files

### ISSUE THREAD

**Issue by sb711** [zefoy/ngx-dropzone-wrapper#107]
Hi,
I was able to manually add files to dropzone component using :
this.dropzone = this.componentRef.directiveRef.dropzone();
this.dropzone.files.push(myFile);

But I am unable to see the thumbnails for these files. How can I achieve that? Please reply asap.

**Comment by sconix** [comment]
This is just a wrapper for Dropzone, so I am not a Dropzone expert and don't know about Dropzone usage so you might have better luck asking in Dropzone related forums.
