### ISSUE TITLE
Error: Can't resolve 'dropzone'

### ISSUE THREAD

**Issue by beyondsanity** [zefoy/ngx-dropzone-wrapper#109]
Hello,

I've just tried to install this library in my ng6 project.
After adding the library I found both dropzone and ngx-dropzone-wrapper folders in my node_modules, but trying to import DropzoneModule result in:
```
ERROR in ./node_modules/ngx-dropzone-wrapper/dist/ngx-dropzone-wrapper.es5.js
Module not found: Error: Can't resolve 'dropzone' in '/Users/[...]/node_modules/ngx-dropzone-wrapper/dist'
```

Am I missing something?

Thanks

**Comment by fergalmoran** [comment]
Seems to be an issue with dropzone itself, I was getting this in a project without ngx-dropzone-wrapper.

Pin dropzone to 5.4.0 and it works.
```
npm install dropzone@5.4.0
```

**Comment by aubrym** [comment]
Hi,

Same problem here.
I trying to use ngx-dropzone-wrapper in a Angular 6 application and I get the error:

ERROR in ./node_modules/ngx-dropzone-wrapper/dist/ngx-dropzone-wrapper.es5.js
Module not found: Error: Can't resolve 'dropzone' in '**************\node_modules\ngx-dropzone-wrapper\dist'

This problem began after the migration of the project from version 5 to version 6 of the angular.

**Comment by IlyaLabarevich** [comment]
Sconix has you checked this?

**Comment by IlyaLabarevich** [comment]
So no way to build, unstable with nmp 6.1 and 6.1 dropzone
And 5.6 nmp 5.x dropzone

**Comment by sconix** [comment]
Just see the comments above, pin dropzone version not the version of this library.

**Comment by aubrym** [comment]
Thank you for you attention @sconix .
How can I the version 5.4.0 of dropzone with ngx-dropzone-wrapper?

**Comment by aubrym** [comment]
I got this working after install dropzone 5.4.0 locally.
Using:
`npm install dropzone@5.4.0`

**Comment by sconix** [comment]
The reason seems to be that the 5.5.0 release of Dropzone seems to be missing the actual js files. Hopefully there is a new release soon, until that just keep using dropzone 5.4.0.

**Comment by IlyaLabarevich** [comment]
So I've solved this on Saturday

solution
npm install (version 6.1.0)
npm install dropzone@5.4.0
npm install ngx-dropzone-wrapper@5.3.5

**Comment by guillaume-ro-fr** [comment]
If you use Yarn, you can add in your `package.json` file : 

```
...
  "resolutions": {
    "dropzone": "5.4.0"
  }
...
```
