### ISSUE TITLE
Use dropzone in *ngFor

### ISSUE THREAD

**Issue by sb711** [zefoy/ngx-dropzone-wrapper#110]
How can I use this dropzone wrapper inside a form element in *ngFor dynamically?

**Comment by sconix** [comment]
Like any other component in Angular.

**Comment by sb711** [comment]
How can I use indexing for all repeated dropzone components in the HTML, ngModel isnt working ?

**Comment by sb711** [comment]
Please help. Do I need to use multiple dropzone configs?

**Comment by sconix** [comment]
It's hard to help when I don't understand the problem. This sound more like question to Angular forums than related to this library.

**Comment by myshanoo** [comment]
How solve ngx dropzone ngfor dynamic data
