### ISSUE TITLE
Uploading a lot of files

### ISSUE THREAD

**Issue by Alados** [zefoy/ngx-dropzone-wrapper#112]
When I try to upload a lot of files (without sending on server) I have problem that a few files are uploaded indefinitely. That occur with 100+ files.
I overrided event totalUploadProgress and got 100% readiness, but event queueComplete isn't invoke at all.

**Comment by sconix** [comment]
You should address that problem in Dropzone forums, this is just a wrapper for Dropzone so only takes care of initializing dropzone and passing in the configuration nothing else.
