### ISSUE TITLE
How should I display default image

### ISSUE THREAD

**Issue by xoco70** [zefoy/ngx-dropzone-wrapper#113]
Hi, 

I would like to display the current avatar inside dropzone. 

With the original component, I would do:

```
myDropzone.on("addedfile", function(file) {
  if (!file.type.match(/image.*/)) {
    myDropzone.emit("thumbnail", file, "http://path/to/image");
  }
});
```

But I don't know how should I do it with Angular...

**Comment by sconix** [comment]
You can do everything like with the original component if you like. This is just a wrapper and only initializes dropzone with given config options. The directive offers method for getting the dropzone instance which can be used exactly like orginal dropzone.
