### ISSUE TITLE
Calling the instance and adding already uploaded files

### ISSUE THREAD

**Issue by asanti82** [zefoy/ngx-dropzone-wrapper#114]
I understand from other comments that you just created the wrapper for which I am thankful.  But if you could atleast shed some light into how to get/call the instance before it's created and add the following code?  This is straight from Dropzone documentation as to how to add already uploaded files:

`// Create the mock file:
var mockFile = { name: "Filename", size: 12345 };

// Call the default addedfile event handler
myDropzone.emit("addedfile", mockFile);

// And optionally show the thumbnail of the file:
myDropzone.emit("thumbnail", mockFile, "/image/url");
// Or if the file on your server is not yet in the right
// size, you can let Dropzone download and resize it
// callback and crossOrigin are optional.
myDropzone.createThumbnailFromUrl(file, imageUrl, callback, crossOrigin);

// Make sure that there is no progress bar, etc...
myDropzone.emit("complete", mockFile);

// If you use the maxFiles option, make sure you adjust it to the
// correct amount:
var existingFileCount = 1; // The number of files already uploaded
myDropzone.options.maxFiles = myDropzone.options.maxFiles - existingFileCount;`

From what I understand "myDropzone" is the created instance, but when going by your example I just added the following: 

`<dropzone 
                                    [config]="dzEditor"
                                    [message]="'Click or drag images here to upload'" 
                                    [useDropzoneClass]="false"
                                    (error)="onUploadError($event)" 
                                    (success)="onUploadSuccess($event)">
                                </dropzone>`

So not sure how to add the prev code to this?

**Comment by sconix** [comment]
See the readme how to get the dropzone instance from the wrapper.

**Comment by sconix** [comment]
It all depends at what phase you are trying to access the reference. So you need to study basic of Angular lifecycle to understand what is available and when.
