### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by rvmladenov** [zefoy/ngx-dropzone-wrapper#120]
Hi,
just a quick question: does ngx-dropzone-wrapper supports Angular 7

**Comment by sconix** [comment]
Yes the major version of this library matches Angular version on purpose to tell that its tested to work with Angular 7 :).

**Comment by kev-landry** [comment]
I can confirm that, i'm currently working on an Angular 7 project using this package and no problems so far.

**Comment by rvmladenov** [comment]
Thank you, you can close that issue
