### ISSUE TITLE
Add init event

### ISSUE THREAD

**Issue by rvmladenov** [zefoy/ngx-dropzone-wrapper#124]
The init event which I am adding in the "config" object is not been called when the Dropzone creates an instance. Is this a bug of some sort or it should be added as event for the directive(I saw that this is not been added there). 
The only way I managed to make it work is to emit an "addedFile" event which in my case is not a solution. Since I have dynamic container and template views I am loading the directive in the "ngAfterViewInit()" using a variable "loaded" which is been set as "true".
But when everything initializes - I can not get reference of the ViewChild for the dropzone directive .

**Comment by sconix** [comment]
Afaik dropzone does not have an init event. At least I can not find such event from the documentation. So to what init event are you referring to?

**Comment by rvmladenov** [comment]
"Init" is actually in the section of "functions you can override to change or extend default behavior:". And it is called when dropzone is initialized. So my mistake, it is not an event. 

It will be great to add what you are suggesting. Some init even upon creation. Thanks :)

**Comment by sconix** [comment]
I added the init event for the 7.2.1 release which is out now.

**Comment by rvmladenov** [comment]
Thank you
