### ISSUE TITLE
Change TimeOut doesnt work

### ISSUE THREAD

**Issue by Gutorov** [zefoy/ngx-dropzone-wrapper#128]
Can`t change 30 seconds timeout, any value in the config dont affects on default value, timeout is 30s always, another properties seems working....
Please LMK how to fix it
```
{
      url: `${environment.apiUrlUploader}`,
      clickable: true,
      maxFiles: 100,
      timeout: 540000,
      retryChunks: true,
      retryChunksLimit: 4,
      maxFilesize: 209715200,
      parallelUploads: 1,
      headers: headers,
 };
```

**Comment by Gutorov** [comment]
version is latest "ngx-dropzone-wrapper": "^7.2.1",

**Comment by Gutorov** [comment]
and after 30s response is http://prntscr.com/mt10x0
but server is not responded.

> Can`t change 30 seconds timeout, any value in the config dont affects on default value, timeout is 30s always, another properties seems working....
> Please LMK how to fix it
> 
> ```
> {
>       url: `${environment.apiUrlUploader}`,
>       clickable: true,
>       maxFiles: 100,
>       timeout: 540000,
>       retryChunks: true,
>       retryChunksLimit: 4,
>       maxFilesize: 209715200,
>       parallelUploads: 1,
>       headers: headers,
>  };
> ```

and after 30s response is http://prntscr.com/mt10x0
but server is not responded.

**Comment by sconix** [comment]
You should report this to Dropzone repo, this is just a wrapper and the config is passed as it is to the Dropzone instance.

**Comment by Gutorov** [comment]
> You should report this to Dropzone repo, this is just a wrapper and the config is passed as it is to the Dropzone instance.

Okay, will try, thx for reply
