### ISSUE TITLE
Dropzone in a list?

### ISSUE THREAD

**Issue by supreettare** [zefoy/ngx-dropzone-wrapper#131]
Hey Guys, 
Is there a proper way to use DropZone in a list/ array? We have a requirement to upload files based on an API. The API returns how many & what files the user needs to upload. 

Based on the number of items in response of the API, we create that many dropzones on the UI. ( Only one div based dropzone element bound to an array of the data. So it repeats as many times as the number of items in the list) 

The issue we are facing is that if we upload one file to one of these dynamically created dropzones, the same file starts appearing on other dropzones too. Which I believe is due to the fact that we are creating them dynamically & somehow it's the same instance rather then having separate instances. 

If this question makes sense, is there a better way to deal with it? 

Thanks for your help in advance. Really Appreciated. 

ST

**Comment by sconix** [comment]
You should ask about this on the Dropzone forums. This is just Angular wrapper so not sure that any Dropzone experts follow these issues.

**Comment by supreettare** [comment]
No worries, we just got it fixed. We just added index of the array item while creating the dropzone in a list so now this creates unique instances. 

Thanks for taking your time to answer this. 

Regards
ST
