### ISSUE TITLE
Dropzone autoDiscovery is on?

### ISSUE THREAD

**Issue by daniel-bikemap** [zefoy/ngx-dropzone-wrapper#134]
As discussed in https://github.com/zefoy/ngx-dropzone-wrapper/issues/129, autoDiscovery should be off. Still, I get an error when initializing dropzone using ngx-dropzone-wrapper:

```
Error: No URL provided. vendor.js line 341 > eval:1066:13
    Dropzone dropzone.js:1066
    discover dropzone.js:2968
    discover dropzone.js:2950
    _autoDiscoverFunction dropzone.js:3516
    init dropzone.js:3484
```

I opted for component usage for the preview image functionality and I provide the URL (along with all the other config) via ngOnInit() since the URL depends on outside factors. I tried providing an mock URL in app.modules.ts, but the error persists.

Is this a bug, or am I holding it wrong? Running on Angular 7.2.10 with ngx-dropzone-wrapper 7.2.1

**Comment by sconix** [comment]
Have you tried doing it in AfterViewInit? The Dropzone is a JS library so it operates in DOM space so I suspect that there might be weird errors sometimes when updating it if DOM is not ready.
