### ISSUE TITLE
Images sent directly from mobile get rotated by 90 degrees.

### ISSUE THREAD

**Issue by radekjakubowski** [zefoy/ngx-dropzone-wrapper#153]
Hello!
I am facing an issue in my project - while I am taking a photo with my mobile holding it vertically it gets uploaded but it is rotated by 90 degrees as I guess to maintain correct aspect ratio.

Is there any workaround to make it work properly?

Here is my dropzone config:
![image](https://user-images.githubusercontent.com/83402116/123589371-66624480-d7e9-11eb-9a7f-dc8860fb9d2e.png)

I am looking forward for your reply!
Cheers,
Radek

**Comment by sconix** [comment]
This would be more of an question for dropzone than for this wrapper.
