### ISSUE TITLE
Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries

### ISSUE THREAD

**Issue by Yamesh1994** [zefoy/ngx-dropzone-wrapper#158]
Angular 13
ng serve 
Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:

 ngx-dropzone-wrapper [es2015/esm2015] (git+https://github.com/zefoy/ngx-dropzone-wrapper.git)

Encourage the library authors to publish an Ivy distribution.

Please update package

**Comment by sconix** [comment]
Updating to Angular 14 this week.
