### ISSUE TITLE
filremoved not getting fired.

### ISSUE THREAD

**Issue by gdevdeiv** [zefoy/ngx-dropzone-wrapper#16]
Hi there,

I have been using this module for a while, and I just wanted to add the "Remove file" option, so my code looks like this right now:

submit.component.ts

```
...

dropzoneSettings = {
    server: 'https://example.com/upload',
    maxFilesize: 20,
    acceptedFiles: 'image/*',
    addRemoveLinks: true
};

...

onFileRemoved(event: any) {
    console.log("Removed.");
    console.log(event);
}

...
```

submit.html

```
...

<dropzone [config]="dropzoneSettings" [message]="'Drag here.'" (error)="onUploadError($event)" (success)="onUploadSuccess($event)" (removedfile)="onFileRemoved($event)" id="dropzonePreview"></dropzone>

...
```

The thing is that the onFileRemoved() function is not getting called. Am I missing something?

**Comment by sconix** [comment]
Everything looks correct, I can quickly check that why its not working later this week.

**Comment by sconix** [comment]
Then you are using an old version.
