### ISSUE TITLE
Initialization error after Angular update

### ISSUE THREAD

**Issue by anottest** [zefoy/ngx-dropzone-wrapper#22]
After updating my project to version 2.4.10 of Angular, the dropzone component started throwing an error during initialization:
Cannot read property 'nativeElement' of undefined

**Comment by sconix** [comment]
We are also using 2.4.10 and I don't see any errors / problems with this library. Are you sure that the problem isn't somewhere else? And are you using the component or directive?

**Comment by anottest** [comment]
Thanks for the reply. I found the issue on our side. I'm extending your component to allow a custom HTML template. Originally it did not define a constructor, but after this update to Angular it needed one defined or else it would no longer call the appropriate constructor defined on your component.
