### ISSUE TITLE
[placeholder] is null after uploading a file

### ISSUE THREAD

**Issue by topa** [zefoy/ngx-dropzone-wrapper#25]
Hi, at first I want to thank you for your nice and easy to use wrapper around dropzone. It really helps me developing my app.
Right now I'm using the `[placeholder]` to show previously uploaded images which works perfectly fine.
But after uploading or changing an image `[placeholder]` becomes `null`. Is this the desired behavior and am I misusing the `[placeholder]`?

**Comment by topa** [comment]
It seems that setting `autoReset` to `0` solved my problem.

**Comment by maheshts** [comment]
i am unable to set placeholder.Can you pls guide.
