### ISSUE TITLE
Please add the withCredentials property to DropzoneConfigInterface.

### ISSUE THREAD

**Issue by SaAkSin** [zefoy/ngx-dropzone-wrapper#26]
related links...

http://definitelytyped.org/docs/dropzone--dropzone/interfaces/dropzoneoptions.html

thank you for your efforts.

**Comment by govorov** [comment]
You can access xhr instance using `sending` event.

**Comment by sconix** [comment]
I don't think that the latest dropzone has withCredentials, afaik it was with the older versions and with newer you need to do it via xhr instance for example.

**Comment by sconix** [comment]
I will close this until somebody proves me wrong that the withCredentials is part of the latest dropzone version.
