### ISSUE TITLE
Working with config autoProcessQueues = false

### ISSUE THREAD

**Issue by KshitizGIT** [zefoy/ngx-dropzone-wrapper#27]
How do I manually process queues ? Is there a event exposed for this?

**Comment by sconix** [comment]
You need to check dropzone documentation. All events and dropzone object are exposed.

**Comment by rafaelss95** [comment]
I was facing the same "_problem_" today, so I found the following [docs](https://github.com/enyo/dropzone/wiki/Combine-normal-form-with-Dropzone) which points me to the right direction.

My config is the following:

```
public config: DropzoneConfigInterface = {
  // ...
  autoProcessQueue: false,
  init: function() {
    const dropzone: any = this;
    document.querySelector('button[type=submit]').addEventListener('click', (event: MouseEvent) => {
      event.preventDefault();
      event.stopPropagation();
      dropzone.processQueue();        
    });
};
```

**Comment by sboyd** [comment]
@sconix thanks for writing this wrapper!

@rafaelss95 and anyone else who has this question the cleaner approach would be the following and they are using the component version.

@ViewChild(DropzoneComponent) componentRef: DropzoneComponent;

//process the queue 
this.componentRef.directiveRef.dropzone.processQueue();

Then you don't need the workaround listed above.
--Steve

**Comment by chenkie** [comment]
Quick edit to @sboyd's answer above, the snippet should be:

```ts
@ViewChild(DropzoneComponent) componentRef: DropzoneComponent;

this.componentRef.directiveRef.dropzone().processQueue();
```

This will get the dropzone instance.

**Comment by sboyd** [comment]
@chenkie my guess is that it depends on the version of the wrapper you are using. I'm using version 4.x.x and the way I get the dropzone instance is what I'd posted in my comment. Now if you're using the same version of the wrapper I'm at a total loss :0)

**Comment by chenkie** [comment]
Ah, I'm on v5. Thanks for clarifying :)

**Comment by sboyd** [comment]
My bad....I should have stated that in the first place.
Have a great day.
--Steve
