### ISSUE TITLE
Not properly working in safari browser.

### ISSUE THREAD

**Issue by RathodGirish** [zefoy/ngx-dropzone-wrapper#28]
Dropzone loading display but image not uploading.
I am trying to upload from iPhone safari browser.

**Comment by sconix** [comment]
I don't think we have had any problems with safari, but I can try next week.

**Comment by RathodGirish** [comment]
Actually I am getting problem when try to reset already uploaded images in safari only. For other browser it's working fine.

`this.dropzone.options.addedfile.call(this.dropzone, mockFile);`

Getting this error:

EXCEPTION: FileConstructor is not a constructor (evaluating 'new File([], _thisPicture.Name)')

**Comment by sconix** [comment]
Ok if you are calling the dropzone functions then you might have better luck in Dropzone issues, I can't see how the Angular part could effect how the Dropzone works internally.

**Comment by RathodGirish** [comment]
ok @sconix 
I am using angular2.
You know What could be the reason? and any other solution?

**Comment by sconix** [comment]
I have no ideas, but let see if we bump into same problem once we start full testing of our upcoming product where we use this library.

**Comment by RathodGirish** [comment]
Thanks
You can try with simple example. And try to reset exiting images in dropzone area.
