### ISSUE TITLE
Remove file triggers

### ISSUE THREAD

**Issue by CleberDSantos** [zefoy/ngx-dropzone-wrapper#29]
I would like it to have support for when I wanted to delete a file, I could request a call to delete it.

I tried to just change to addRemoveLinks: true, however nothing happens.

**Comment by sconix** [comment]
Can you be bit more specific. Are you using directive or component and what do you mean that nothing happens. The add / remove links wont show or don't work?

**Comment by TcQPAD** [comment]
Hello, I'm facing a similar issue using the dropzone component, I've set 

> addRemoveLinks: true

in my configs, but the removeLinks won't work, i.e., when hovering cancel/remove nothing happpens and clicking them won't work.

 The configs are working: 

![dropzone_remove_bug](https://user-images.githubusercontent.com/17066590/28284492-70144772-6b31-11e7-8096-422c8d073017.PNG)


I noticed the remove link is out of its div container, is-it intended?

![remove_dropzone_bug_ui](https://user-images.githubusercontent.com/17066590/28284674-152cce1e-6b32-11e7-85c7-ce835ae758b1.PNG)

**Comment by sconix** [comment]
I don't think the addRemove links does anything else than add the links, you need to handle the removal etc in the remove callback etc.

If that wont solve it I can look into this bit closely once I am back from my holiday on monday.
