### ISSUE TITLE
Can't set 'headers' option

### ISSUE THREAD

**Issue by Nixon-Joseph** [zefoy/ngx-dropzone-wrapper#30]
Hello! This wrapper is amazing, first off. Just having one issue. I am using OAuth, and I require headers on every api call, including  file uploads. When I set the config - like so:
`public getImageConfig(): DropzoneConfigInterface {
        if (!this.dzImageConfig) {
            this.dzImageConfig = {
                server: this.apiBaseUrl + '/File/image',
                maxFilesize: this.maxFileSize,
                acceptedFiles: 'image/*',
                headers: this.getHeader(),
                renameFilename: (filename) => (new Date().getTime() + '_' + filename)
            };
        }
        return this.dzImageConfig
    }

 private getHeader(): Headers {
        let headers = new Headers(),
            profJson = localStorage.getItem('profile'),
            profile = this.isValidJson(profJson) ? JSON.parse(profJson) : new Token();
        headers.append('Content-Type', 'application/json');
        headers.append('Authorization', 'Bearer ' + profile.access_token);
        return headers;
    }`
and then try to upload a file, the console blows up with this error:
`Uncaught DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'function (name, value) {
        var /** @type {?} */ values = this.getAll(name);
        if (values === null) {
            this.set(name, value);
        }
        else {
            values.push(value);
        }
    }' is not a valid HTTP header field value.`

Everything works fine without the headers being set (aside from not being able to authorize the sender).

Thanks!

**Comment by sconix** [comment]
Dropzone does not support headers as function. I am planning to add such support at some point to the wrapper itself, but for now you just need to update the header object in the config when ever something header related changes.

In our application we use time to keep the firebase authentication token uptodate in the configuration which naturally is not the ideal so adding support for getting header config through function is pretty high on my list.

**Comment by Nixon-Joseph** [comment]
Alright, so just to make sure I understand this correctly. I can't assign
the headers through a function. Does that mean that I can use that same
function to create the headers on a variable and assign headers to that
variable? Or that I have to create the whole configuration object, and then
append the headers?

Thanks!

**Comment by sconix** [comment]
Sorry I did not look your example closely enough. I see now that you generate the config and headers only once so then you don't have the same issue than us.

Now when I looked your example more closely your problem is that you are using Angular http Headers object, Dropzone headers needs to be just regular object. Now Dropzone tries to convert Angular http Headers object into xmlHttRequest headers and that causes the error.

**Comment by Nixon-Joseph** [comment]
Ohhhhh alright. Thanks! I should be able to figure that out.

Have a great day :)

**Comment by malchijah** [comment]
Hi @Nixon-Joseph I ran into the same issue. How did you fix this? Please share the solution if it's working for you.

**Comment by krutik-dhameliya** [comment]
Okay so what is the solution, how do we add header in dropzone configuration ?

**Comment by cizaquita** [comment]
Hi,

I'm using **keycloak-angular** that sets automatically the token for authorization in every HTTP request.
So, I just noted that ngx-dropzone-wrapper does not do this.

I need to add the Authorization header for ngx-dropzone-wrapper when upload files.

Any suggestion? Thanks

**Comment by smaillns** [comment]
As @sconix said, jsut add the Authorization bearer to the headers object, like this
```
config: DropzoneConfigInterface = {
    url: `${environment.backendUrl}/uploads`,
    paramName: 'uri',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  };
```
