### ISSUE TITLE
withCredentials request option

### ISSUE THREAD

**Issue by baha2jo** [zefoy/ngx-dropzone-wrapper#31]
Im not able to use withCredentials request option in the dropzone configuration

**Comment by sconix** [comment]
There is no such option in latest Dropzone.

**Comment by troolee** [comment]
Hi @sconix, they do have `withCredentials` option:

https://github.com/enyo/dropzone/blob/7d0792d1346d83a8b0c0d2919121bdd2b8e7fee4/dist/dropzone-amd-module.js#L131

**Comment by sconix** [comment]
Seems that they have add it back. I will make a new release with support for that configuration option.
