### ISSUE TITLE
add CSV extension to acceptedFile's list

### ISSUE THREAD

**Issue by dlodeprojuicer** [zefoy/ngx-dropzone-wrapper#35]
How do I configure the plugin to accept .csv files? Its working as expected if acceptedFiles: 'image/*' I changed acceptedFiles to 'csv/*', '.csv/*', '.csv' and 'csv' trying to make it work for CSV files but it is not working.

How do I change the config to accept CSV files?

```const DROPZONE_CONFIG: DropzoneConfigInterface = {
  server: 'https://httpbin.org/post',
  maxFilesize: 50,
  acceptedFiles: 'csv'
};```

**Comment by sconix** [comment]
You need to figure out the correct mime type for the file. I think that csv is text/csv, but not sure.

**Comment by dlodeprojuicer** [comment]
@sconix text/csv worked, thank you.

**Comment by tatsujb** [comment]
for me `text/csv` dosen't. `*` doesn't either.

I get : 
![image](https://user-images.githubusercontent.com/5132359/37409106-d09ba012-279d-11e8-9126-7e59e33aacb5.png)

**Comment by tatsujb** [comment]
removing the `acceptedFiles` line from the config entirely fixed it for me. now I accept all files.
