### ISSUE TITLE
'server' no longer implemented in DropzoneConfigInterface

### ISSUE THREAD

**Issue by michalrames** [zefoy/ngx-dropzone-wrapper#38]
As far as I can tell the 'server' property was removed from DropzoneConfigInterface in 4.5.x 

Changelog is not included and the README.md still shows instruction to use 'server'.

Can you please clarify the changes and the correct way of using this library in 4.5.2?

Thank you

**Comment by michalrames** [comment]
I think I found the solution in the examples .... the propery was renamed to `url`

**Comment by sconix** [comment]
Sorry, forgot to mention that. The server was a legacy param which was removed. The parameter has always been url in dropzone sonI removed the additional legacy parameter support. I will update the readme.
