### ISSUE TITLE
How to use .emit() event?

### ISSUE THREAD

**Issue by murilobd** [zefoy/ngx-dropzone-wrapper#40]
Hi,
I'm trying to reproduce this (https://github.com/enyo/dropzone/wiki/FAQ#how-to-show-files-already-stored-on-server) with ngx-dropzone-wrapper:

```
// Create the mock file:
var mockFile = { name: "Filename", size: 12345 };

// Call the default addedfile event handler
myDropzone.emit("addedfile", mockFile);

// And optionally show the thumbnail of the file:
myDropzone.emit("thumbnail", mockFile, "/image/url");
// Or if the file on your server is not yet in the right
// size, you can let Dropzone download and resize it
// callback and crossOrigin are optional.
myDropzone.createThumbnailFromUrl(file, imageUrl, callback, crossOrigin);

// Make sure that there is no progress bar, etc...
myDropzone.emit("complete", mockFile);
```

How could I do that .emit() with ngx-dropzone-wrapper?

**Comment by sconix** [comment]
The Dropzone object is exposed as public member named 'dropzone' within the directive. So you can access it through the directive reference (if you are using component there is directiveRef available from through the component reference) using ViewChild.

**Comment by murilobd** [comment]
That's true @sconix ! Thanks buddy!

**Comment by murilobd** [comment]
If someone get's the same issue, here's how I solved:

**component.html**
```
<dropzone #dropzonePicture  [config]="dropzoneProfessionalPictureConfig">				</dropzone>
```

**component.ts**
```
@ViewChild('dropzonePicture') dropzonePicture: DropzoneComponent;

someMethod() {
    this.dropzonePicture.directiveRef.dropzone.emit(...);
}
```

**Comment by archish1989** [comment]
@murilobd By following your example i am getting emit() is undefined error. can you help me?

**Comment by murilobd** [comment]
hey @archish1989, could you put your code on a gist or somewhere else so I could take a look?

**Comment by dreamid27** [comment]
@archish1989 do you have an example about this question ?

i really new in angular, and i dont know how to transform it.
