### ISSUE TITLE
Remove/update dependency on @angular/http

### ISSUE THREAD

**Issue by Erikvv** [zefoy/ngx-dropzone-wrapper#41]
https://github.com/zefoy/ngx-dropzone-wrapper/blob/master/src/lib/dropzone.module.ts

HttpModule from `@angular/http` is deprecated and replaced by HttpClientModule from `@angular/common`

I don't understand why the dependency is there, since Dropzone.js use XMLHttpRequest directly. So maybe it can just be removed?

**Comment by sconix** [comment]
Its just left over from some really old code, will remove. Thanks.
