### ISSUE TITLE
How to use reset() Function in angular way. 

### ISSUE THREAD

**Issue by nileshyadav326** [zefoy/ngx-dropzone-wrapper#42]
**Hi I want to call reset()  click of submit button or any other event** 

Available control / helper functions (provided by the directive):

reset()  // Resets the dropzone upload area (removes all finished preview files).

below is my code .html file

`<dropzone [config]="config" [message]="'Click or drag images here to upload'" (error)="onUploadError($event)" (success)="onUploadSuccess($event)" (complete)="onUploadComplete($event)" ></dropzone>`

and .componet file.

```
public config: DropzoneConfigInterface = {
        paramName: 'inputFiles',
        addRemoveLinks:true
    };
    
    

    onUploadError(args: any) {
        console.log('onUploadError:', args);
    }

    onUploadSuccess(args: any) {
        console.log('onUploadSuccess:', args);
    }
    
    onUploadComplete(args: any) {
       console.log('onUploadComplete:', args); 
       this.reset();
    }
```

**Comment by sconix** [comment]
Like you would call any component functions in Angular. Have a look at the example app code if you are new to Angular.

**Comment by wasiff** [comment]
HTML:
<dropzone 
              [config]="config" 
              [message]="'Click or drag images here to upload'" 
              (drop)="onFileDropped($event)"
              (sending)="onSending($event)"
              (error)="onUploadError($event)"
              (success)="onUploadSuccess($event, dz)"
              (removeFile)="onRemoveFile($event)"
              #dz>
            </dropzone>

Component.ts
@ViewChild('dz') drpzone: DropzoneComponent;

this.drpzone.directiveRef.reset()
this.drpzone.directiveRef.dropzone();
