### ISSUE TITLE
when i drag and drop any files it is redirecting one url (post req)

### ISSUE THREAD

**Issue by AmitAKB** [zefoy/ngx-dropzone-wrapper#46]
When I drag and drop files it is redirecting one URL. I don't want to this url. I want this files convert into front end no need to back-end.
Any possibility available this drag and drop without AJAX calls files convert into front end.

Please provide the solutions on this?

**Comment by sconix** [comment]
You need to check the Dropzone documentation, it should have support for frontend preview.

**Comment by AmitAKB** [comment]
But i upload the CSV file using dropzone. So i want to preview in front end.

**Comment by sconix** [comment]
As I said you need to check Dropzone documentation, dropzone provides events for every phase so that you can process files before / without upload. But if you are not doing upload at all then you might want to look into file reader libraries since dropzone is build for uploading files and might not be the best fit for what you want to do.

**Comment by AmitAKB** [comment]
When i upload the CSV file it is hitting https://httpbin.org/post this url. i dont want to hit this url and i want only result of CSV file without hitting this url.

**Comment by sconix** [comment]
What I have tried to say is that Dropzone is about uploading and if you just need file reader there are libraries for that. You might be able to do what you want with thia but you need to look into Dropzone docs how to capture the file events before file upload. Dont know if possible but i think so.

**Comment by sconix** [comment]
You could try asking in dropzone issues. Thus question is not about this library since this is just angular wrapper and this question is about droozone usage and not specific to angular and this library.
