### ISSUE TITLE
Cannot access to server response from onFailed() event

### ISSUE THREAD

**Issue by lvidal1** [zefoy/ngx-dropzone-wrapper#49]
When `onFailed()` event is fired I can not read the server response. `$event` just only passes Request metadata.

**Current Behavior**

This is what my server responses on `500 status`

![seleccion_018](https://user-images.githubusercontent.com/6495076/30406826-f824f778-98b9-11e7-9e2f-c6ce35cb9196.png)

This is what I receive from the  `(error)="onUploadError($event)" `

![seleccion_017](https://user-images.githubusercontent.com/6495076/30406918-aa3ab8f8-98ba-11e7-8f28-9282b40da20a.png)

I expanded all the properties from the $event param but any of them seems to wrap the server response
**Do I have to use another param to access to the server response? or how can I using $event?**  I'd appreciate your response.

**Comment by sconix** [comment]
The XMLHttpRequest is the javascript request object that holds also the response data. See XMLHttpRequest documentation for more info.

**Comment by lvidal1** [comment]
@sconix as I mentioned, I also looked for the response in XMLHttpRequest, but it seems to be empty. I think this object is not filled properly after the upload.

This is how XMLHttpRequest looks like onFailed() event

![seleccion_019](https://user-images.githubusercontent.com/6495076/30437158-8a7cd7de-9933-11e7-91f4-f436fc7d6efd.png)

**Comment by sconix** [comment]
I think something else is wrong, the object should be the normal javascript xml request object so I have no idea how it could be not filled. That response code 0 is bit odd and there seems to be issues for dropzone with that response so maybe have a look from the dropzone issues if there is a solution for you. This wrapper really does not touch touch those events they are as the dropzone sends them.
