### ISSUE TITLE
how to custom css of element dropzone

### ISSUE THREAD

**Issue by at-dungvan** [zefoy/ngx-dropzone-wrapper#51]
#### how to custom css of element dropzone
My app has config `maxFiles = 1`, so the dropzone has view like this
![screenshot from 2017-09-22 14-29-03](https://user-images.githubusercontent.com/11406553/30733725-6d204994-9fa2-11e7-8b5c-4e3f652fe52e.png)

 but i want to show view like this if i reset css of class .dz-text to 
```css
.dz-text {
  margin-top: 0px;
  transform: none;
}
```
![screenshot from 2017-09-22 14-30-52](https://user-images.githubusercontent.com/11406553/30733787-b356aa84-9fa2-11e7-8455-2cd107418183.png)

how cant i config the dropzone with my style on class .dz-text?

sorry for my bad english and big thanks.

**Comment by at-dungvan** [comment]
i resole this problem with 
```html
[useDropzoneClass]="false"
```
thanks!

**Comment by sconix** [comment]
Yeah using that input its possible to disable the default styles when you can always provide your own. But of course you can override styles even if that true, then you just need to learn how CSS works and how to  make selectors overpower existing selectors.

**Comment by fergalmoran** [comment]
This method removes all styling though? I'm having the same issue but when I try 
`
.dz-text {
  margin-top: 0px!important;
}
`
It has no effect?

**Comment by djanesch** [comment]
@fergalmoran you have to insert a space between values and !important.
your code should look like the following:
`.dz-text { margin-top: 0px !important; }`

**Comment by fergalmoran** [comment]
@djanesch Sorry but that's just a typo - I did have a space in my actual CSS.
Thanks for the tip though!!

**Comment by sconix** [comment]
Are you using some old version of the library? The latest does not use margin-top to position the text.

**Comment by fergalmoran** [comment]
@sconix I'm pretty sure I tried it recently with the latest version and found the same behaviour.
I've moved on to something else just now - I'll get back to this soon and if I see the same problem, I'll open a new issue with full details. Thanks for your input guys!

**Comment by sconix** [comment]
The point being was that if you set margin-top: 0 !important it wont help anything with the new version since the margin is 0 as a default. The position of the text is setting using transform.

**Comment by fergalmoran** [comment]
Ok, well that definitely explains the behaviour I was seeing. Thanks for the explanation.
