### ISSUE TITLE
'dictRemoveFileConfirmation' does not exist in type 'DropzoneConfigInterface'.

### ISSUE THREAD

**Issue by archish1989** [zefoy/ngx-dropzone-wrapper#52]
`
import { DropzoneModule } from 'ngx-dropzone-wrapper';
import { DropzoneConfigInterface,DropzoneComponent } from 'ngx-dropzone-wrapper';
const DROPZONE_CONFIG: DropzoneConfigInterface = {
dictRemoveFileConfirmation: true,

// Change this to your upload POST address:
url: environment.apiurl+'/product/media',
maxFilesize: 50,
method: 'post',
acceptedFiles: 'image/*',
headers:{'Cache-Control': null,
'X-Requested-With': null},
paramName: 'media[]',
addRemoveLinks: true,
createImageThumbnails: true,
};`

this is my sample code, i want to set confirmation as documented here:

http://www.dropzonejs.com/#config-dictRemoveFileConfirmation

but i am getting error when i set value for dictRemoveFileConfirmation.

this is error which i am getting:

>Type '{ dictRemoveFileConfirmation: boolean; url: string; maxFilesize: number; method: string; accepted...' is not assignable to type 'DropzoneConfigInterface'.
Object literal may only specify known properties, and 'dictRemoveFileConfirmation' does not exist in type 'DropzoneConfigInterface'.
please help.

**Comment by archish1989** [comment]
`        
import { DropzoneModule } from 'ngx-dropzone-wrapper';
import { DropzoneConfigInterface,DropzoneComponent } from 'ngx-dropzone-wrapper';    
             const DROPZONE_CONFIG: DropzoneConfigInterface = {
             dictRemoveFileConfirmation: true,

  // Change this to your upload POST address:
  url: environment.apiurl+'/product/media',
  maxFilesize: 50,
  method: 'post',
  acceptedFiles: 'image/*',
  headers:{'Cache-Control': null,
        'X-Requested-With': null},
  paramName: 'media[]',
  addRemoveLinks: true,
  createImageThumbnails: true,
};`

this is my sample code, i want to set confirmation as documented here: 

http://www.dropzonejs.com/#config-dictRemoveFileConfirmation

but i am getting error when i set value for dictRemoveFileConfirmation.

this is error which i am getting:

> Type '{ dictRemoveFileConfirmation: boolean; url: string; maxFilesize: number; method: string; accepted...' is not assignable to type 'DropzoneConfigInterface'.
  Object literal may only specify known properties, and 'dictRemoveFileConfirmation' does not exist in type 'DropzoneConfigInterface'.

please help.

**Comment by sconix** [comment]
Seems to be new dict parameter which is missing from the interface file. I added it and release new version 4.6.3.
