### ISSUE TITLE
acceptedFiles between Mac and Window give different result

### ISSUE THREAD

**Issue by corelationNut** [zefoy/ngx-dropzone-wrapper#53]
Hi,

currently i'm add acceptedFiles option into dropzone config with "text/csv", when I'm upload via Mac Chrome it's working fine. But when I'm upload via Window (Window 7) Chrome, dropzone show an error "You can't upload file of this type".

So has anyone face this issue, or how to fix this one ? 

chrome version: (both os use same version)
Version 61.0.3163.100 (Official Build) (64-bit)

model config:

> acceptedFiles: "text/csv"
> autoReset: null
> cancelReset: null
> clickable: true
> errorReset: null
> maxFiles: 1
> maxFilesize: 100
> params: {allocationtype: 0}
> url: "upload"

ngx-dropzone-wrapper version: 4.6.2

Thanks,
Nuttakron.

**Comment by sconix** [comment]
That you need to ask in Dropzone issues. This is just a wrapper for Dropzone.
