### ISSUE TITLE
No url provided, dropzone already attached

### ISSUE THREAD

**Issue by gate3** [zefoy/ngx-dropzone-wrapper#54]
Hello. I am gettint these errors while trying to use the libary. I would appreciate any help please

**Comment by sconix** [comment]
Like the error says you need to provide the url in the configuration.

**Comment by gate3** [comment]
hi, I'd like to handle the image upload on my own. I used autoprocess
false, but it's still the same thing.

**Comment by sconix** [comment]
I don't know if Dropzone can be used in such way, but you can look into Dropzone documentation / ask in its issues if such thing is possible.

**Comment by gate3** [comment]
I've used dropzone for such task in the past and all I needed to do was
specify autoprocess false.

**Comment by sconix** [comment]
Ok, well hopefully somebody has an answer for you, but you might have better luck asking in Dropzone project.

**Comment by neilxc** [comment]
I had the same issue with the Dropzone already attached.  I had to import Dropzone and add the Dropzone.autoDiscover flag to false in the constructor (or on init).  This resolves the error.  The URL error will go away if you specify a URL in the config.    

 ```
 public config: DropzoneConfigInterface = {
    url: `http://localhost:5000/api/users/${this.authService.decodedToken.nameid}/photos`,
    clickable: true,
    maxFiles: 2,
    autoReset: null,
    errorReset: null,
    cancelReset: null,
    headers: {'Authorization': 'Bearer ' + this.token}
  };

  constructor(private authService: AuthService) {
    Dropzone.autoDiscover = false;
  }
```
Don't forget to import Dropzone:  

`import * as Dropzone from 'dropzone';`

**Comment by sconix** [comment]
This library sets the autoDiscover to false.

**Comment by gate3** [comment]
@neilxc thanks, will try it out.

**Comment by gate3** [comment]
Hi @neilxc thanks so much. Your suggestion worked, I also specified a string 'no-url' as the url. @sconix Thanks a lot for the attempt. Much appreciated. God bless
