### ISSUE TITLE
How to use dropzone wrapper for particular components individually.

### ISSUE THREAD

**Issue by ils-rajnikantd** [zefoy/ngx-dropzone-wrapper#55]
Hello,
I have used this module and it is a very good one.
But the problem I faced that, if I have different upload pages and each having there own upload path, so in that case how can I do this using this wrapper.

Because this wrapper is globally defined and all the upload field uses only one upload URL, but in my case I want different upload URL should be passed to each individual upload interface.

Please help me in this issue.

Thanks

**Comment by sconix** [comment]
Just check the README, you can have separate configuration for each component.

**Comment by ils-rajnikantd** [comment]
Thanks Sconix,

But README doen't have any information regarding the local configurations for wrapper, it only have the option for global configuration.

**Comment by sconix** [comment]
It does have the inputs explained for giving configuration for the component.

**Comment by sconix** [comment]
It does have the inputs explained for giving configuration for the component.

[config]            // Custom config to override the global defaults.

**Comment by ils-rajnikantd** [comment]
Hi Sconix,

I am aware all the things whichever written in the README, but I a not very much familiar with this and not able to understand how to pass the different URL with every wrapper or directives we use.

Let see the example.

I have a component customer products, where I use this wrapper and global URL set for the product URL
Now, I also have one other component customer profile, where I use this wrapper again, but not able to set the URL for the component customer profile. I wanted that customer profile URL should be profile.

Now, as mentioned in README, there is [config] = "config" but we do not have any specific details that what is config and how to configure this.

I am very getting confused and not able to configure the different URLs for different component or directives.

**Comment by ils-rajnikantd** [comment]
Hi Sconix,

Now I am able to configure different URLS successfully.

However, I am getting one error in browser console that "Dropzone already attached."

Thanks

**Comment by sconix** [comment]
That should be just an warning. Anyway the next version will fix that or you can already fix it by doing the following:

Dropzone.autoDiscover = false;

**Comment by ils-rajnikantd** [comment]
Thanks!

**Comment by sconix** [comment]
Release 4.6.6 while ago fixing that so will close this now.
