### ISSUE TITLE
Is ngx-dropzone-wrapper support multiple files upload with separate urls?

### ISSUE THREAD

**Issue by annguyenew** [zefoy/ngx-dropzone-wrapper#56]
Hello,
First of all, this angular wrapper is amazing.
But for my case, I want to bulk upload(multiple files) at a time or upload a directory. For each file, I must make an API call to the server to get upload URL.
Is there any way that I can pass the appropriate URL for each selected files?

**Comment by sconix** [comment]
You would need to ask that in Dropzone issues, or at least I think you have better change getting answer there. I am not a dropzone expert, but I suspect that its possible.

**Comment by annguyenew** [comment]
Thank @sconix,
I will look for the solution in Dropzone issues.
