### ISSUE TITLE
Upload to AWS s3 bucket using a Pre-signed URL

### ISSUE THREAD

**Issue by rahulbagal** [zefoy/ngx-dropzone-wrapper#58]
Hi , 

I am using this library and trying to upload file to AWS s3 bucket using a Pre-signed URL. 
I need to implement something like below . How do I implement it ? 

new Dropzone(element, {
  url: pre_signed_upload_url,
  method: "PUT",
  headers: {"Content-Type": "image/jpeg"},
  sending: function(file, xhr) {
    var _send = xhr.send;
    xhr.send = function() {
      _send.call(xhr, file);
    };
  }
});

Ref:  [Lendar's comment ](https://github.com/enyo/dropzone/issues/590)

**Comment by sconix** [comment]
Its the same with this library there is no difference. This just wraps Dropzone so anything you can set in the Dropzone config you can set in this library config and it gets passed directly to Dropzone when its created.
