### ISSUE TITLE
Error metadata

### ISSUE THREAD

**Issue by JarekSour** [zefoy/ngx-dropzone-wrapper#61]
Hi !!
I work with angular 4.2.4 and when execute, i receve this error "... found version 4, expected 3 ..."
any solution ??

best regards

**Comment by sconix** [comment]
Yes you have wrong version of this library, the major version needs to match your Angular version as stated in the README.

**Comment by JarekSour** [comment]
@sconix so this file https://github.com/zefoy/ngx-dropzone-wrapper/tree/4.x.x
is deprecated ??

![screenshot_1](https://user-images.githubusercontent.com/5225945/32877482-87f9b850-ca80-11e7-8d5a-448e2be79685.png)

**Comment by sconix** [comment]
I don't understand your question. If you are using Angular 4 you need to use 4.x version of this library. Your error comes from you trying to use 5.x version of this library.

**Comment by JarekSour** [comment]
@sconix , I using angular 4 and i follow the documentation 4.x of the library, and i receive that error  
"... found version 4, expected 3 ..." , more simply?? regards.

**Comment by sconix** [comment]
I thought that it would be clear enough if its stated that you need to install the version 4.x, but I guess I need to update the README to have the exact install instruction then.
