### ISSUE TITLE
Example does not work in Safari 11.0

### ISSUE THREAD

**Issue by lukeify** [zefoy/ngx-dropzone-wrapper#65]
Using Safari Version 11.0.1 (13604.3.5) on macOS 10.13.1, your example webpage does not load. No error is presented in the console to indicate what's going on. Screenshot attached :)

![screen shot 2017-12-04 at 11 42 50 am](https://user-images.githubusercontent.com/5379845/33530811-e65b3dd4-d8e9-11e7-8e3f-52fd67eede66.png)

**Comment by sconix** [comment]
At least it works for me with Safari 11.0.1.

**Comment by sconix** [comment]
I also tried with exact  same OSX and Safari version and there was no problem loading the example. So closing this as not an issue.

**Comment by lukeify** [comment]
@sconix Appears to be an issue when uBlock Origin is installed. Disabling it makes it work. I'll raise it with them.
