### ISSUE TITLE
'addedfile' event not fired

### ISSUE THREAD

**Issue by yunielgarcia** [zefoy/ngx-dropzone-wrapper#68]
I'm using `"ngx-dropzone-wrapper": "^4.7.0",` I need to make some file validation when the file is added.
In my html:
` 
          <dropzone [config]="dropzoneConfigI"

                    [message]="'Click or drag images here to upload'"

                    (error)="onError($event)"

                    (sending)="onSending($event)"

                    (sendingmultiple)="onSendingmultiple($event)"

                    (success)="onSuccess($event)"

                    (addedfile)="onAddedFile($event)"

          >
          </dropzone>
`
the controller:

`

  public dropzoneConfigI: DropzoneConfigInterface = {

    url: environment.apiUrl + '/content',

    clickable: true,

    autoReset: null,

    errorReset: null,

    cancelReset: null,

    paramName: 'content',

    acceptedFiles: '',

    autoProcessQueue: false,

    addRemoveLinks: true

  };

  @ViewChild(DropzoneComponent) componentRef: DropzoneComponent;

  onAddedFile(data): void {

    console.log('onAddedFile');

// making some validation here

  }
  onError(data): void {

    console.log('onError');

  }`

error event is working along with others that I'm using but now addedfile stopped working.
I also put a couple of break point in the console:
`
        if (('addedfile' === en)) {

          var pd_8 = (_co.DZ_ADDEDFILE.emit($event) !== false);

          ad = (pd_8 && ad);

        }

        if (('error' === en)) {

          var pd_9 = (_co.DZ_ERROR.emit($event) !== false);

          ad = (pd_9 && ad);

        }
`

'addedfile' is never hit.
Am I missing something, here? I'm using Angular 4.4.6 . Thanks in advance.

**Comment by sconix** [comment]
It seems that I made an error backporting the support for latest dropzone from the 5.x versions. I will release a new version to fix the issue.

**Comment by sconix** [comment]
There is no 4.8.0 out that has proper event handling. Sorry about the mistake.

**Comment by GuitooStephan** [comment]
I am using ngx-dropzone-wrapper 8.0.0
And I am facing this problem
