### ISSUE TITLE
Passing function to URL config doesn't work

### ISSUE THREAD

**Issue by patadv** [zefoy/ngx-dropzone-wrapper#69]
I'm using Firebase Storage on the backend and after reading the Dropzone documentation it says this under the URL config, "You can also provide a function that will be called with files and must return the url (since v3.12.0)." This is also the case for 'method'. 

I've attempted passing a function into the URL but wasn't succeeding. Typescript was saying it isn't valid for starters. I took a look at the DropzoneConfigInterface and it shows only strings are allowed. Since Dropzone docs say this isn't true, I updated it to also allow Functions. 

Now the passed in function runs with each File object. Cool! But not all is totally well. It appears dropzone wrapper is taking the returned file source URL and using that as a URL endpoint which throws an error. 

Edit: The error ends up breaking upload interface so any chance the wrapper can be updated to support passed in functions for URL & method config options in a future release? 

Thanks!

**Comment by sconix** [comment]
It seems that I have missed that they can be functions. I will make a new release later today.

**Comment by sconix** [comment]
What do you mean by this:

It appears dropzone wrapper is taking the returned file source URL and using that as a URL endpoint 
which throws an error

I don't quite get it. The interface need to be updated for sure, but I don't think there is nothing else since the wrapper wont use the configuration itself.

**Comment by patadv** [comment]
Sure. Indeed that wasn't totally clear. My interpretation of the error is that the return URL from the function is being used as the address for the POST request, which obviously doesn't work. I could be mistaken, though. 

Here's a screenshot of the called function running and the error that immediately follows upon uploading an image. I'm returning a static URL to mimic the uploaded image URL.

(https://user-images.githubusercontent.com/15081309/33847249-6422cec8-de56-11e7-85aa-22b62b1143fe.jpg)

**Comment by sconix** [comment]
Hmm but the url is supposed to be the endpoint for the request... Well anyway I don't think that is related to this so I will release the new version with the proper interface soon. At least then it should be up to the Dropzone and not about this wrapper.

**Comment by patadv** [comment]
Just to clarify how I'm using it, there should be no POST request at all while uploading. I'm using the Firebase Storage library in a separate function (called by the URL config field) and dropzone doesn't need to execute anything from a returned result or no returned result. Ideally, no network request should be called by Dropzone throughout this entire process because the function is doing all that work. 

I just tried the dropzone URL function without returning a string and it tried to send a POST request to undefined. 

Error: POST http://localhost:4200/undefined 404 (Not Found)

Perhaps this is the fault of Dropzone and not the wrapper. Thanks for looking into it and being so responsive!!

**Comment by sconix** [comment]
No problem. Yes its a limitation of Dropzone then or maybe there is a way who knows. Maybe try asking in Dropzone issues. Anyway I will release the new version with support for the functions, thanks for reporting the problem.

**Comment by mchampaneri** [comment]
@patadv 

Do you get any solution regard this issue? 
I would like to know solution, if you found any.

Thanks ,
Manish
