### ISSUE TITLE
Error building angular application with ngx-dropzone-wrapper

### ISSUE THREAD

**Issue by MRebati** [zefoy/ngx-dropzone-wrapper#70]
hello,
I get an Error over building the application.
which is:
`node_modules/ngx-dropzone-wrapper/dist/ngx-dropzone-wrapper.d.ts, found version 4, expected 3, resolving symbol AppModule in "AppModule FileAddress"`.

My angular package versions are 4.2.4. and the package version is 5.0.0

**Comment by sconix** [comment]
As the almost very first line of the README says that you need 4.x version of this package for the older versions of Angular.
