### ISSUE TITLE
Events are not firing   "ngx-dropzone-wrapper": "5.3.0"

### ISSUE THREAD

**Issue by dangerian** [zefoy/ngx-dropzone-wrapper#72]
div class="dropzone scrollDiv" [dropzone]="config" (error)="onUploadError($event)" (success)="onUploadSuccess($event)" (addedfile)="onAddedFile($event)" 

my onAddedFile($event)"  function isnt  firing after the upgrade from 4.6.6.  

The file properties dont have the dataURL  property any more. How do I get access to the at information without autoProcessQueue set to true

**Comment by sconix** [comment]
Check the readme for events naming. For the dataURL you need to check Dropzone documentation.

**Comment by debojyoti** [comment]
@dangerian 
It should be` (addedfile)="yourCustomFunction($event)"`
