### ISSUE TITLE
Update dropzone to 5.3.0

### ISSUE THREAD

**Issue by baschny** [zefoy/ngx-dropzone-wrapper#76]
Dropzone 5.3.0 fixes the annoying drag&drop issue in Safari and IE, so if nothing speaks against it, I suggest to update the dependency to that version.

See https://gitlab.com/meno/dropzone/blob/v5.3.0/CHANGELOG.md

**Comment by sconix** [comment]
Thanks, will make new release with updated dependency version. Of course you can already install the newer dropzone and the wrapper should be happy with it.
