### ISSUE TITLE
reset doesn't remove files

### ISSUE THREAD

**Issue by sefo** [zefoy/ngx-dropzone-wrapper#77]
```
<dropzone [config]="dropzoneConfig" #dropZone></dropzone>
<button (click)="resetMe()">RESET</button>
```

```
  @ViewChild('dropZone') dropZone;
   this.dropZone.filesDrop = [];
   this.dropZone.reset();
```
I drag and drop files in the dropzeone. They're added correctly to the component.
After submitting the form I try to  reset the dropzone with the above code.
I tried a mix of different things, nothing works.

There's a "removeFiles" method somewhere but not on that dropZone component...

**Comment by sconix** [comment]
Your code does not look right. Have a look at the example app code. You can get the dropzone instance by calling dropzone() from the directiveRef.
