### ISSUE TITLE
Problems with the disabled Input

### ISSUE THREAD

**Issue by GRTO** [zefoy/ngx-dropzone-wrapper#79]
I have some problems with the disabled option. I wrote this code:

`<dropzone *ngIf="type === 'component'" class="dropzone-container" [config]="config" [disabled]="disabled" fxLayout="row" fxLayoutAlign="start strech" fxFlex="auto" [message]="'Click or drag images here to upload'" (error)="onUploadError($event)" (success)="onUploadSuccess($event)"></dropzone>`

I set **disabled** as true, when i run my app you can upload some files, but i think it wouldn't. It happens when you set trur the disabled. Can you have a look at it? 

I was working with your example
[https://stackblitz.com/github/zefoy/ngx-dropzone-wrapper/tree/master/example?file=src%2Fapp%2Fapp.component.html]()

**Comment by sconix** [comment]
There was a bug that the disabled state was not checked on init, I released a new version to fix this. Thanks for reporting this.
