### ISSUE TITLE
dropzone reference

### ISSUE THREAD

**Issue by waseemnasir9** [zefoy/ngx-dropzone-wrapper#82]
i am getting an error using the method suggested to get dropzone reference. im using angular 5 with latest version of this wrapper. i want to send files on click of button

import {NgForm} from '@angular/forms';
import { DropzoneModule, DropzoneComponent, DropzoneDirective, DropzoneConfigInterface } from 'ngx-dropzone-wrapper';
@Component({
  selector: 'app-description',
  templateUrl: './description.component.html',
  styleUrls: ['./description.component.css']
})
export class DescriptionComponent implements OnInit {
  @ViewChild(DropzoneDirective) directiveRef: DropzoneDirective;
	
    public config: DropzoneConfigInterface = {

      url: 'http://localhost:52905/uploadfiles',
      maxFilesize: 5,
      acceptedFiles: 'image/*',
      autoProcessQueue: false,
      uploadMultiple: true
    
    };`

**onclick:** 

`onSubmit(desc :Description){
    console.log(desc.Detail);
    let dropzone =  this.directiveRef.dropzone();
   dropzone.processQueue();          
               
  }`

**html:**
`<div class="dropzone" [dropzone]="config" (error)="onUploadError($event)" `(success)="onUploadSuccess($event)"></div>`

![screenshot 3](https://user-images.githubusercontent.com/37339175/37349119-5f20fb22-26de-11e8-99b2-f0b4f4924cb4.png)

**Comment by sconix** [comment]
Only reason should be that you are trying to call it before Angular has connected the ViewChild. Where does the onSubmit call come and can it come before view has been initialized?

**Comment by waseemnasir9** [comment]
<form class="description-form" #descriptionForm="ngForm" (ngSubmit)="onSubmit(descriptionForm.value)">
												<input type="hidden"  name="descriptionId" #descriptionId="ngModel" [(ngModel)]="description.Id" >

									
											..i have some other fields here
				
														
													<div class="dropzone" [dropzone]="config" (error)="onUploadError($event)" (success)="onUploadSuccess($event)"></div>

												
												<button [disabled]="!descriptionForm.valid" type="submit" class="btn btn-success btn-primary" ><i class="fa fa-check"></i> Create</button>
												
												</form>


this is my form 
in my dependencies i have 

`"ngx-dropzone-wrapper": "^4.9.0",`

and i ran this command as well 

`npm update ngx-dropzone-wrapper --save`

**Comment by sconix** [comment]
So you don't have latest version. When you use ^ it only installs latest minor version not major. So you need to set it to ^5.0.0 to get the latest version.

**Comment by waseemnasir9** [comment]
sorry i just found about this. updated it to 5 now it works. thank you very much. Also the upload progress bar or green check does not appear. i only know through onuploadsuccess(). can i overcome this?

**Comment by sconix** [comment]
I don't remember all the dropzone options that what does what, but I know that the example app has those so maybe have a look at that if you have something different in your options.

**Comment by waseemnasir9** [comment]
alright thanks
