### ISSUE TITLE
Themeing

### ISSUE THREAD

**Issue by tatsujb** [zefoy/ngx-dropzone-wrapper#84]
is it also possible to theme the dropzone?
with this : 
`<dropzone [message]="'Click or drag images here to upload'"></dropzone>`

I've got this : 
![image](https://user-images.githubusercontent.com/5132359/37403128-10c741c4-278e-11e8-8de5-7df67e3f556f.png)

it's not anywhere near as good as what's shown here : 
http://www.dropzonejs.com/#

the blue borders are now grey, there's no rounded edges and the min-height is so small that a scrollbar shows up for *one line of text*

also the added files are below the add zone rather than within (which is more instinctive) : 
![image](https://user-images.githubusercontent.com/5132359/37403806-55fffe32-2790-11e8-8dff-4f8688c219a3.png)

I'd like to customize this without building the whole theme back up from scratch. ergo I don't want to use `[useDropzoneClass]="false"`

**Comment by sconix** [comment]
You can style everything normally with CSS no special tricks needed so just override the parts that you don't like. I only provide the Dropzone default styles within the library there are no ready made themes included etc.

**Comment by tatsujb** [comment]
actually I can't. I don't know how you do it but my style get overridden (rather deleted) it shows up nowhere in the inspector in the served version of the app. 

Is it a question of ordering the entries in angular-cli.json? 

what's causing the style to get worse than overridden?

**Comment by tatsujb** [comment]
for example : 

```
.dz-message{
    border: 2px dashed rgb(0, 135, 247) !important;
    border-radius: 5px !important;
    min-height: 100px !important;
}
```
Dissaperation! magic : 

![image](https://user-images.githubusercontent.com/5132359/37407461-fa495160-2799-11e8-934c-3b82e912bc6f.png)

**Comment by sconix** [comment]
For that you need to learn basic CSS and how the CSS selectors work etc.

**Comment by tatsujb** [comment]
? how so? if a div a class name you can select it, and do stuff to it, am I wrong?

I'll be the first to admit the road to knowledge has no end and I still have a long way to go but i think a basic knowledge of CSS is an understatement of what I have. I'm using Scss with variable, extends, imports and so on.

**Comment by tatsujb** [comment]
oh ok. it's basically a component like my own component and the style is scoped within it. 

Now I have to figure out how to access it or rather unscope.

**Comment by tatsujb** [comment]
for those searching it's : 
```
 /deep/ .dz-message {
    border: 2px dashed rgb(0, 135, 247) !important;
    border-radius: 5px !important;
    min-height: 100px !important;
  }
```
or with `:host /deep/ .dz-message {`  or `:host-context /deep/ .dz-message {`

**Comment by thenaadiyaahmed** [comment]
Thank you! 
This is actually a really important issue. Styling your components individually.

**Comment by trollanfer** [comment]
/deep/ is deprecated, instead you can  add this in app.component.ts

`import {ViewEncapsulation} from '@angular/core'; 

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  encapsulation: ViewEncapsulation.None 
})`

Then the css will access dropzone without /deep/

**Comment by KikoCosmetics** [comment]
I think this should be reopened and a solution should be provided at least to disable the default styling. 
I can make a PR if you want.

![image](https://user-images.githubusercontent.com/93335982/193576118-fe70e58a-320f-4968-ae57-a9ab5bd9078a.png)
