### ISSUE TITLE
header

### ISSUE THREAD

**Issue by mihaipopescu0409** [zefoy/ngx-dropzone-wrapper#85]
if i am trying to add a authorization header like this:

```
 url: `${environment.baseURL}/api/routing/version/${this.version.ID}/content/zip`,
 headers: {
    Authorization: `Bearer ${this.adal.userInfo.token}`
 },
 acceptedFiles: '.zip'
```
the field hiddenFileInput is empty, and i get this error: Uncaught TypeError: Cannot read property 'files' of null

If i am not passing the header parameter, everything works, but i am getting 401 from the server. 

Any suggestions?

**Comment by j99ht** [comment]
Same thing happens here. Any news on this?

**Comment by mihaipopescu0409** [comment]
@j99ht i couldn't find a solution, so i ended up using dropzone without this wrapper

**Comment by sconix** [comment]
This wrapper passes in the configuration for the Dropzone as it is so this question is about how to use Dropzone and not about this wrapper.

**Comment by VereeckenJamie** [comment]
Same problem here:

Template
```
<dropzone [message]="'Click or drag files to upload'" (success)="_handleUploadSuccess($event)"
                  (error)="_handleUploadError($event)" [config]="createDropzoneHeader()"></dropzone>
```

Function
```
  createDropzoneHeader() {
    return {
      headers: {
        Authorization: `Bearer ${this.authService.getToken().access_token}`
      }
    };
  }
```

With the headers set the result I get is `Uncaught TypeError: Cannot read property 'files' of null`

**Comment by sconix** [comment]
The problem with your solution is that actually creates new config object so dropzone gets re-initialized every time the config changes. So this wrapper just re-initializes dropzone when ever config object changes. So you need to have your config option stored in your component and only update the headers inside that config and not create new config object each time.

**Comment by VereeckenJamie** [comment]
Thanks, that seems to work :)

**Comment by cizaquita** [comment]
> Same problem here:
> 
> Template
> 
> ```
> <dropzone [message]="'Click or drag files to upload'" (success)="_handleUploadSuccess($event)"
>                   (error)="_handleUploadError($event)" [config]="createDropzoneHeader()"></dropzone>
> ```
> 
> Function
> 
> ```
>   createDropzoneHeader() {
>     return {
>       headers: {
>         Authorization: `Bearer ${this.authService.getToken().access_token}`
>       }
>     };
>   }
> ```
> 
> With the headers set the result I get is `Uncaught TypeError: Cannot read property 'files' of null`
> 
> UPDATE: It only seems to happen when I set the "headers" in the config of the component. When I set the headers globally (in the app.module.ts) there are no problems.

Can you explain how did you does it?

My auth token refresh every 300ms, so I need to dynamically set the bearer token on every update. 

The library does not allow me to do this when the component init, it gets the first configuration I set.
