### ISSUE TITLE
maxFile:1 // the image occupy the full page

### ISSUE THREAD

**Issue by HADDADENICAR** [zefoy/ngx-dropzone-wrapper#93]
When i set the configuration of dropzone " **maxFiles** " in angular to accept only one file , the preview of the image take the full page.
However when the " **maxFiles** " is set to accept 2 or more files the preview is ok (just like trying in the Dropzone.js web site)

what should i do to fix that problem ?

**Comment by sconix** [comment]
Sounds like a styling issue. Are you using component or directive?

**Comment by HADDADENICAR** [comment]
component

**Comment by sconix** [comment]
The component has special styles for having maxFiles set to one. So some styles in your application is interfering with those styles so you need to either fix the styles or you could use the directive that does not have any special additional styles (only the default styles from dropzone).

**Comment by HADDADENICAR** [comment]
Yes, i changed the style inside the component ("width" and "height") and it has resolved the problem.
but now , i prefer using the directive it works without any problem.
thanks
