### ISSUE TITLE
url: 'https://httpbin.org/post',//with what should it be changed

### ISSUE THREAD

**Issue by HADDADENICAR** [zefoy/ngx-dropzone-wrapper#96]
hello,
i need to send an image to a node.js server, so i have changed the url to this : 'http://192.168.1.5:2000/api/v1/products', but i get **'Server responded with 0 code'**

**Comment by sconix** [comment]
That depends on your upload server implementation that how to configure Dropzone. Anyway for dropzone configuration you need to refer Dropzone documentation, this just wraps Dropzone so I don't have the required knowledge of Dropzone internals that how that works.
